export enum StimulsoftSourceName {
  STIMULSOFT_DESIGNER = 'STIMULSOFT_DESIGNER',
  STIMULSOFT_REPORTER = 'STIMULSOFT_REPORTER',
  STIMULSOFT_VIEWER = 'STIMULSOFT_VIEWER',
  CSS_STIMULSOFT_DESIGNER = 'CSS_STIMULSOFT_DESIGNER',
  CSS_STIMULSOFT_VIEWER = 'CSS_STIMULSOFT_VIEWER',
}
