export enum StimulsoftSourceName {
  DESIGNER_SCRIPT = 'DESIGNER_SCRIPT',
  REPORTER_SCRIPT = 'REPORTER_SCRIPT',
  VIEWER_SCRIPT = 'VIEWER_SCRIPT',
  DESIGNER_STYLE = 'DESIGNER_STYLE',
  VIEWER_STYLE = 'VIEWER_STYLE',
}
